language: node_js
node_js:
  - '14'
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '5.9'
  - '5.8'
  - '5.7'
  - '5.6'
  - '5.5'
  - '5.4'
  - '5.3'
  - '5.2'
  - '5.1'
  - '5.0'
  - '4.4'
  - '4.3'
  - '4.2'
  - '4.1'
  - '4.0'
script:
  - 'make lint && make test-ci'
after_script:
  - 'npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls'
